config/routes.rb
Rails.application.routes.draw do
  resources :cartoons

   root 'cartoons#index'

end

app/models/cartoon.rb
class Cartoon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController

  def index
    @cartoons = Cartoon.all
  end

  def show
    @cartoon = Cartoon.find(params[:id])
  end

  def new
    @cartoon = Cartoon.new(onair: true)
  end

  def create
       @cartoon = Cartoon.new(cartoon_params)

    if @cartoon.save
      redirect_to cartoons_path, notice: "Cartoon Added"
    else
      # Cartoon is invalid
      render :new
    end
  end

  def edit
    @cartoon = Cartoon.find(params[:id])
  end

  def update
    @cartoon = Cartoon.find(params[:id])

    if @cartoon.update(cartoon_params)
      redirect_to cartoons_path, notic: "Cartoon Updated"
    else
      render :edit
    end

  end

  def destroy
    @cartoon = Cartoon.find(params[:id])
    @cartoon.destroy
    redirect_to cartoons_path, notice: "Cartoon Destroy"
  end

  def cartoon_params
    params.require(:cartoon).permit(:name, :characters, :photo_url, :onair, :dvd_price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/views/cartoons/_form.html.erb
<%= form_for(@cartoon) do |f| %>
  <% if @cartoon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cartoon.errors.count, "error") %> prohibited this cartoon from being saved:</h2>

      <ul>
      <% @cartoon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :characters %><br>
    <%= f.text_area :characters %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :dvd_price %><br>
    <%= f.text_field :dvd_price %>
  </div>
  <div class="field">
    <%= f.label :onair %><br>
    <%= f.check_box :onair %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cartoons/edit.html.erb
<h1>Editing cartoon</h1>

<%= render 'form' %>

<%= link_to 'Show', @cartoon %> |
<%= link_to 'Back', cartoons_path %>

app/views/cartoons/index.html.erb
<h1>Listing cartoons</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Characters</th>
      <th>Photo url</th>
      <th>Onair</th>
      <th>DVD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartoons.each do |cartoon| %>
      <tr>
        <td><%= cartoon.name %></td>
        <td><%= cartoon.characters %></td>
        <td><%= image_tag cartoon.photo_url, class: 'thumbnail' %></td>
        <td><%= cartoon.onair %></td>
        <td>$<%= cartoon.dvd_price %></td>
        <td><%= link_to 'Show', cartoon %></td>
        <td><%= link_to 'Edit', edit_cartoon_path(cartoon) %></td>
        <td><%= link_to 'Destroy', cartoon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartoon', new_cartoon_path %>

app/views/cartoons/new.html.erb
<h1>New cartoon</h1>

<%= render 'form' %>

<%= link_to 'Back', cartoons_path %>

app/views/cartoons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cartoon.name %>
</p>

<p>
  <strong>Characters:</strong>
  <%= @cartoon.characters %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @cartoon.photo_url %>
</p>

<p>
  <strong>Onair:</strong>
  <%= @cartoon.onair %>
</p>


<%= link_to 'Edit', edit_cartoon_path(@cartoon) %> |
<%= link_to 'Back', cartoons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartoons</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>